### ISSUE TITLE
No --help flag available

### ISSUE THREAD

**Issue by Mafrans** [ekwoka/create-PETT-app#1]
create-PETT-app doesn't have any --help flag, which breaks the ["Help" CLI Guideline](https://clig.dev/#help). Consider adding a help message which conforms to the guidelines.

**Comment by ekwoka** [comment]
This is a fantastic idea! 👍

**Comment by ekwoka** [comment]
Solved in https://github.com/ekwoka/create-PETT-app/pull/2#event-7095888834
